FROM debian:12

ENV DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        wget \
        tar \
        unzip \
        jq \
        xvfb \
        xauth \
        x11-utils \
        procps \
        gosu \
        wine \
        wine32 \
        wine64 \
        winbind \
        cabextract \
        lib32gcc-s1 \
        lib32stdc++6 \
        libcurl4-gnutls-dev:i386 \
        libsdl2-2.0-0:i386 \
        libtinfo6:i386 \
        libncurses6:i386 \
        libstdc++6:i386 \
        zlib1g:i386 && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/steamcmd /opt/games/server /opt/games/config /opt/wine /home/gnp && \
    useradd -m -u 1000 -s /bin/bash gnp && \
    chown -R gnp:gnp /opt/steamcmd /opt/games /opt/wine /home/gnp

USER gnp
WORKDIR /opt/steamcmd

RUN wget -q https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz && \
    tar -xzf steamcmd_linux.tar.gz && \
    rm steamcmd_linux.tar.gz && \
    ./steamcmd.sh +quit || true

USER root

COPY scripts/ /scripts/
RUN chmod +x /scripts/*.sh

# ----------------------------
# GNP Standard Variables
# ----------------------------
ENV GNP_TZ="Europe/Paris"
ENV GNP_PUID="1000"
ENV GNP_PGID="1000"

ENV GNP_STEAM_APP_ID="2857200"
ENV GNP_STEAM_USER="anonymous"
ENV GNP_STEAM_PASSWORD=""
ENV GNP_GAME_UPDATE="true"
ENV GNP_VALIDATE_FILES="false"
ENV GNP_STEAM_FORCE_PLATFORM="windows"

ENV GNP_SERVER_NAME="GNP Abiotic Factor Server"
ENV GNP_SERVER_PASSWORD=""
ENV GNP_ADMIN_PASSWORD=""
ENV GNP_MAX_PLAYERS="6"
ENV GNP_WORLD_SAVE_NAME="Cascade"

ENV GNP_GAME_PORT="7777"
ENV GNP_QUERY_PORT="27015"

ENV GNP_USE_PERF_THREADS="true"
ENV GNP_DISABLE_ASYNC_LOADING_THREAD="false"
ENV GNP_NO_ASYNC_LOADING_THREAD="false"
ENV GNP_LAN_ONLY="false"
ENV GNP_PLATFORM_LIMITED=""
ENV GNP_MULTIHOME=""
ENV GNP_USE_LOCAL_IPS="false"
ENV GNP_SANDBOX_INI_PATH="Config/WindowsServer/GNPSandboxSettings.ini"
ENV GNP_ADMIN_INI_PATH=""

ENV GNP_WRITE_SANDBOX_CONFIG="true"
ENV GNP_SANDBOX_GAME_DIFFICULTY="1"
ENV GNP_SANDBOX_HARDCORE_MODE="False"
ENV GNP_SANDBOX_LOOT_RESPAWN_ENABLED="False"
ENV GNP_SANDBOX_POWER_SOCKETS_OFF_AT_NIGHT="True"
ENV GNP_SANDBOX_DAY_NIGHT_CYCLE_STATE="0"
ENV GNP_SANDBOX_DAY_NIGHT_CYCLE_SPEED_MULTIPLIER="1.0"
ENV GNP_SANDBOX_WEATHER_FREQUENCY="3"
ENV GNP_SANDBOX_SINK_REFILL_RATE="1.0"
ENV GNP_SANDBOX_FOOD_SPOIL_SPEED_MULTIPLIER="1.0"
ENV GNP_SANDBOX_REFRIGERATION_EFFECTIVENESS_MULTIPLIER="1.0"
ENV GNP_SANDBOX_STORAGE_BY_TAG="True"
ENV GNP_SANDBOX_STRUCTURAL_SUPPORT_LIMIT="5"
ENV GNP_SANDBOX_BRIDGE_SUPPORTS="2"
ENV GNP_SANDBOX_HOME_WORLDS="True"
ENV GNP_SANDBOX_INVISIBLE_RADIATION="False"
ENV GNP_SANDBOX_TAINTED_SINK_WATER="False"
ENV GNP_SANDBOX_RADIATION_DEALS_DAMAGE="False"
ENV GNP_SANDBOX_ENEMY_SPAWN_RATE="1.0"
ENV GNP_SANDBOX_ENEMY_HEALTH_MULTIPLIER="1.0"
ENV GNP_SANDBOX_ENEMY_PLAYER_DAMAGE_MULTIPLIER="1.0"
ENV GNP_SANDBOX_ENEMY_DEPLOYABLE_DAMAGE_MULTIPLIER="1.0"
ENV GNP_SANDBOX_DETECTION_SPEED_MULTIPLIER="1.0"
ENV GNP_SANDBOX_ENEMY_ACCURACY="2"
ENV GNP_SANDBOX_DAMAGE_TO_ALLIES_MULTIPLIER="0.5"
ENV GNP_SANDBOX_HUNGER_SPEED_MULTIPLIER="1.0"
ENV GNP_SANDBOX_THIRST_SPEED_MULTIPLIER="1.0"
ENV GNP_SANDBOX_FATIGUE_SPEED_MULTIPLIER="1.0"
ENV GNP_SANDBOX_CONTINENCE_SPEED_MULTIPLIER="1.0"
ENV GNP_SANDBOX_BONUS_PERK_POINTS="0"
ENV GNP_SANDBOX_PLAYER_XP_GAIN_MULTIPLIER="1.0"
ENV GNP_SANDBOX_ITEM_STACK_SIZE_MULTIPLIER="1.0"
ENV GNP_SANDBOX_ITEM_WEIGHT_MULTIPLIER="1.0"
ENV GNP_SANDBOX_ITEM_DURABILITY_MULTIPLIER="1.0"
ENV GNP_SANDBOX_DURABILITY_LOSS_ON_DEATH_MULTIPLIER="0.1"
ENV GNP_SANDBOX_SHOW_DEATH_MESSAGES="True"
ENV GNP_SANDBOX_ALLOW_RECIPE_SHARING="True"
ENV GNP_SANDBOX_ALLOW_PAGERS="True"
ENV GNP_SANDBOX_ALLOW_TRANSMOG="True"
ENV GNP_SANDBOX_DISABLE_RESEARCH_MINIGAME="False"
ENV GNP_SANDBOX_DEATH_PENALTIES="1"
ENV GNP_SANDBOX_FIRST_TIME_STARTING_WEAPON="0"
ENV GNP_SANDBOX_HOST_ACCESS_PLAYER_CORPSES="True"
ENV GNP_SANDBOX_ALLOW_CHARACTER_RESET="True"
ENV GNP_SANDBOX_BASE_INVENTORY_SIZE="12"
ENV GNP_SANDBOX_PLAYER_FURNITURE_DESTRUCTION="False"
ENV GNP_SANDBOX_ALLOW_IRON_MODE="True"

ENV GNP_USE_WINE="true"
ENV GNP_WINEPREFIX="/opt/wine/abiotic-factor"
ENV GNP_WINEARCH="win64"
ENV GNP_DISPLAY=":99"
ENV GNP_XVFB_RESOLUTION="1024x768x16"
ENV GNP_WINEDEBUG="-all"

ENV GNP_SERVER_EXE="AbioticFactorServer-Win64-Shipping.exe"
ENV GNP_START_ARGS=""

WORKDIR /opt/games/server

EXPOSE 7777/udp
EXPOSE 27015/udp
EXPOSE 14001/udp

HEALTHCHECK --interval=30s --timeout=10s --start-period=180s --retries=3 CMD /scripts/healthcheck.sh

ENTRYPOINT ["/scripts/entrypoint.sh"]
